# Generated by Django 5.1 on 2024-09-02 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('employee_id', models.IntegerField(unique=True)),
                ('clocked_in', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['first_name'],
                'indexes': [models.Index(fields=['employee_id'], name='timeclock_e_employe_2c7047_idx'), models.Index(fields=['clocked_in'], name='timeclock_e_clocked_932fa2_idx'), models.Index(fields=['last_name', 'first_name'], name='timeclock_e_last_na_733d5c_idx'), models.Index(fields=['employee_id', 'clocked_in'], name='timeclock_e_employe_8122a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in_time', models.DateTimeField()),
                ('clock_out_time', models.DateTimeField(blank=True, null=True)),
                ('hours_worked', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('notes', models.TextField(blank=True, null=True)),
                ('full_day', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeclock.employee')),
            ],
            options={
                'verbose_name': 'Time Entry',
                'verbose_name_plural': 'Time Entries',
                'ordering': ['clock_in_time'],
                'indexes': [models.Index(fields=['employee'], name='timeclock_t_employe_9f0e54_idx'), models.Index(fields=['clock_in_time'], name='timeclock_t_clock_i_3b68bd_idx'), models.Index(fields=['clock_out_time'], name='timeclock_t_clock_o_2d3acf_idx'), models.Index(fields=['hours_worked'], name='timeclock_t_hours_w_132d2f_idx'), models.Index(fields=['full_day'], name='timeclock_t_full_da_1c379a_idx'), models.Index(fields=['employee', 'clock_in_time', 'clock_out_time', 'hours_worked', 'full_day'], name='timeclock_t_employe_e3a5f7_idx')],
            },
        ),
    ]
