# Generated by Django 5.1 on 2024-09-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0005_remove_timeentry_notes_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='created_by',
        ),
        migrations.AddField(
            model_name='timeentry',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
