# Generated by Django 5.1 on 2024-09-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0008_alter_note_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='holiday_hours_allocated',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='employee',
            name='holiday_hours_used',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='is_holiday',
            field=models.BooleanField(default=False),
        ),
    ]
