# Generated by Django 5.1 on 2024-09-04 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0009_employee_holiday_hours_allocated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='holiday_hours_allocated',
            new_name='vacation_hours_allocated',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='holiday_hours_used',
            new_name='vacation_hours_used',
        ),
    ]
