# Generated by Django 5.1 on 2024-09-04 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0010_rename_holiday_hours_allocated_employee_vacation_hours_allocated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeentry',
            old_name='is_holiday',
            new_name='is_vacation',
        ),
    ]
