# Generated by Django 5.1 on 2024-09-09 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0011_rename_is_holiday_timeentry_is_vacation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='force_password_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='sick_hours_allocated',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='employee',
            name='sick_hours_used',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='is_sick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['user', 'employee_id'], name='timeclock_e_user_id_cb8fbb_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['clocked_in', 'last_name'], name='timeclock_e_clocked_49ba39_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['created_at'], name='timeclock_n_created_fb0c48_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['employee', 'clock_in_time'], name='timeclock_t_employe_87586d_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['is_sick'], name='timeclock_t_is_sick_9ddc09_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['is_vacation'], name='timeclock_t_is_vaca_1919a7_idx'),
        ),
    ]
