# Generated by Django 5.1 on 2024-09-09 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0012_employee_force_password_change_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['start_date'], name='timeclock_e_start_d_15098e_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['start_date', 'last_name'], name='timeclock_e_start_d_cb5c7a_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['sick_hours_used', 'sick_hours_allocated'], name='timeclock_e_sick_ho_be5b86_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['vacation_hours_allocated', 'vacation_hours_used'], name='timeclock_e_vacatio_a47d8d_idx'),
        ),
    ]
