# Generated by Django 5.1 on 2024-09-09 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0013_employee_start_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='timeclock_e_start_d_15098e_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='timeclock_e_start_d_cb5c7a_idx',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='start_date',
            new_name='hire_date',
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['hire_date'], name='timeclock_e_hire_da_3b0279_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['hire_date', 'last_name'], name='timeclock_e_hire_da_4b0381_idx'),
        ),
    ]
