# Generated by Django 5.1 on 2024-09-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0014_remove_employee_timeclock_e_start_d_15098e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
