# Generated by Django 5.1 on 2024-09-09 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0015_employee_last_reset_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='timeclock_e_employe_2c7047_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='timeclock_e_clocked_932fa2_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='timeclock_e_last_na_733d5c_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='timeclock_e_employe_8122a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='timeclock_e_user_id_cb8fbb_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='timeclock_e_clocked_49ba39_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='timeclock_e_sick_ho_be5b86_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='timeclock_e_vacatio_a47d8d_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='timeclock_e_hire_da_3b0279_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='timeclock_e_hire_da_4b0381_idx',
        ),
    ]
