# Generated by Django 5.1 on 2024-09-09 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0017_alter_employee_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='timeentry',
            name='timeclock_t_employe_e3a5f7_idx',
        ),
        migrations.AlterField(
            model_name='employee',
            name='sick_hours_allocated',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sick_hours_used',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='employee',
            name='vacation_hours_allocated',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='employee',
            name='vacation_hours_used',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='hours_worked',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['last_reset_date'], name='timeclock_e_last_re_d3b08a_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['employee', 'is_sick', 'is_vacation'], name='timeclock_t_employe_fed1d3_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['clock_in_time', 'is_vacation'], name='timeclock_t_clock_i_a43692_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['clock_in_time', 'is_sick'], name='timeclock_t_clock_i_7d4a3e_idx'),
        ),
    ]
