# Generated by Django 5.1 on 2024-09-09 19:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0018_remove_timeentry_timeclock_t_employe_e3a5f7_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='background_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['background_image'], name='timeclock_e_backgro_711346_idx'),
        ),
    ]
