# Generated by Django 5.1 on 2024-09-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0019_employee_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='vacation_allocated_on_90_days',
            field=models.BooleanField(default=False),
        ),
    ]
