# Generated by Django 5.1 on 2024-10-16 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0021_employee_initial_sick_hours_allocated'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='timeclock_e_clocked_932fa2_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='timeclock_e_employe_8122a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='timeclock_e_user_id_cb8fbb_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='timeclock_e_clocked_49ba39_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='timeclock_e_hire_da_4b0381_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='timeclock_e_sick_ho_be5b86_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='timeclock_e_vacatio_a47d8d_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='timeclock_e_last_re_d3b08a_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='timeclock_e_backgro_711346_idx',
        ),
        migrations.RemoveIndex(
            model_name='note',
            name='timeclock_n_created_fb0c48_idx',
        ),
        migrations.RemoveIndex(
            model_name='timeentry',
            name='timeclock_t_clock_o_2d3acf_idx',
        ),
        migrations.RemoveIndex(
            model_name='timeentry',
            name='timeclock_t_hours_w_132d2f_idx',
        ),
        migrations.RemoveIndex(
            model_name='timeentry',
            name='timeclock_t_full_da_1c379a_idx',
        ),
        migrations.RemoveIndex(
            model_name='timeentry',
            name='timeclock_t_employe_87586d_idx',
        ),
        migrations.RemoveIndex(
            model_name='timeentry',
            name='timeclock_t_employe_fed1d3_idx',
        ),
        migrations.RemoveIndex(
            model_name='timeentry',
            name='timeclock_t_clock_i_a43692_idx',
        ),
        migrations.RemoveIndex(
            model_name='timeentry',
            name='timeclock_t_clock_i_7d4a3e_idx',
        ),
    ]
