# Generated by Django 5.1 on 2024-10-28 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0022_remove_employee_timeclock_e_clocked_932fa2_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
