# Generated by Django 5.1 on 2024-10-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0023_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
    ]
