# Generated by Django 5.1 on 2024-10-28 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0024_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['time_entry', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='timeentry',
            options={'ordering': ['-clock_in_time', 'employee__last_name'], 'verbose_name': 'Time Entry', 'verbose_name_plural': 'Time Entries'},
        ),
    ]
