# Generated by Django 5.1 on 2024-11-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0028_timeoffrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='entry_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('vacation', 'Vacation'), ('sick', 'Sick Leave'), ('holiday', 'Holiday')], default='regular', max_length=10),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='is_holiday',
            field=models.BooleanField(default=False),
        ),
    ]
