# Generated by Django 5.1 on 2024-11-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0029_timeentry_entry_type_timeentry_is_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoffrequest',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='is_partial_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
