# Generated by Django 5.1 on 2024-11-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0030_timeoffrequest_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='future_sick_hours_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='employee',
            name='future_vacation_hours_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='request_type',
            field=models.CharField(choices=[('vacation', 'Vacation'), ('sick', 'Sick Leave'), ('unpaid', 'Unpaid Leave')], max_length=20),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='review_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
    ]
