# Generated by Django 5.1 on 2024-11-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0031_employee_future_sick_hours_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='skip_hours_deduction',
            field=models.BooleanField(default=False),
        ),
    ]
