# Generated by Django 5.1 on 2024-11-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0033_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('none', 'None'), ('print', 'Print'), ('embroidery', 'Embroidery'), ('engraving', 'Engraving'), ('fulfillment', 'Fulfillment'), ('shipping', 'Shipping / Receiving'), ('other', 'Other')], default='none', max_length=20),
        ),
    ]
