# Generated by Django 5.1 on 2024-11-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0034_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='entry_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('vacation', 'Vacation'), ('sick', 'Sick Leave'), ('holiday', 'Holiday'), ('cs', 'Customer Service'), ('it', 'IT')], default='regular', max_length=10),
        ),
    ]
