# Generated by Django 5.1 on 2024-12-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0037_alter_timeentry_entry_type_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='theme_id',
            field=models.CharField(default='light', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='theme_id',
            field=models.CharField(default='light', max_length=50),
        ),
        migrations.DeleteModel(
            name='UserPreferences',
        ),
    ]
