# Generated by Django 5.1 on 2024-12-05 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0040_alter_passwordresettoken_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
