# Generated by Django 5.1 on 2025-01-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0044_ratelimitviolation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratelimitviolation',
            name='level1_count',
        ),
        migrations.RemoveField(
            model_name='ratelimitviolation',
            name='level1_reset',
        ),
        migrations.RemoveField(
            model_name='ratelimitviolation',
            name='level2_count',
        ),
        migrations.RemoveField(
            model_name='ratelimitviolation',
            name='level2_reset',
        ),
        migrations.RemoveField(
            model_name='ratelimitviolation',
            name='level3_count',
        ),
        migrations.RemoveField(
            model_name='ratelimitviolation',
            name='level3_reset',
        ),
        migrations.AddField(
            model_name='ratelimitviolation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ratelimitviolation',
            name='rehabilitation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ratelimitviolation',
            name='ban_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ratelimitviolation',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
    ]
