# Generated by Django 5.1 on 2025-01-06 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0045_remove_ratelimitviolation_level1_count_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RateLimitViolation',
        ),
    ]
