# Generated by Django 5.1 on 2025-01-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0046_delete_ratelimitviolation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
                ('ban_level', models.IntegerField(blank=True, choices=[(1, 'Level 1 - 10 minute ban'), (2, 'Level 2 - 1 hour ban'), (3, 'Level 3 - 1 day ban'), (4, 'Level 4 - Permanent ban')], null=True)),
                ('ban_start', models.DateTimeField(blank=True, null=True)),
                ('ban_end', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-attempt_time'],
                'indexes': [models.Index(fields=['ip_address', 'attempt_time'], name='timeclock_p_ip_addr_b83904_idx')],
            },
        ),
    ]
