# Generated by Django 5.1 on 2025-01-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0047_passwordresetattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetattempt',
            name='attempt_type',
            field=models.CharField(choices=[('attempt', 'Attempt'), ('ban', 'Ban')], default='attempt', max_length=10),
        ),
        migrations.AddIndex(
            model_name='passwordresetattempt',
            index=models.Index(fields=['attempt_type'], name='timeclock_p_attempt_c5a2f0_idx'),
        ),
    ]
