# Generated by Django 5.1 on 2025-01-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0048_passwordresetattempt_attempt_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
                ('attempt_type', models.CharField(choices=[('attempt', 'Login Attempt'), ('ban', 'Ban Record')], max_length=10)),
                ('ban_level', models.IntegerField(blank=True, null=True)),
                ('ban_start', models.DateTimeField(blank=True, null=True)),
                ('ban_end', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address', 'attempt_time'], name='timeclock_l_ip_addr_25d104_idx'), models.Index(fields=['ip_address', 'attempt_type'], name='timeclock_l_ip_addr_74d018_idx')],
            },
        ),
    ]
