# Generated by Django 5.1 on 2025-01-07 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0051_delete_loginattempt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordresetattempt',
            old_name='grace_period_end',
            new_name='escalation_window_end',
        ),
    ]
