# Generated by Django 5.1 on 2025-01-08 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0052_rename_grace_period_end_passwordresetattempt_escalation_window_end'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetAttempt',
        ),
    ]
